server:
  port: 8081

spring:
  application:
    name: mcp-client-chatbot
  ai:
    open-ai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.2
    mcp:
      client:
        streamable-http:
          connections:
            server1:
              url: http://localhost:8080/mcp

