services:
  demo-ui:
    build:
      context: .
      dockerfile: demo-ui/Dockerfile
    depends_on:
      mcp-client:
        condition: service_healthy
    container_name: demo-ui
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  mcp-client:
    build:
      context: .
      dockerfile: mcp-client-chatbot/Dockerfile
    depends_on:
      fluxnova-service:
        condition: service_healthy
    container_name: mcp-client
    ports:
      - "8083:8080"
      - "5007:5005"
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/actuator/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  fluxnova-service:
    build:
      context: .
      dockerfile: fluxnova-service/Dockerfile
    container_name: fluxnova-service
    ports:
      - "8084:8084"
      - "5008:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - fluxnova_h2:/data/h2
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8084/actuator/health",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  fluxnova_h2:
    driver: local
